server:
  port: 18083

spring:
  application:
    name: brand-service
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: jdbc:h2:mem:musinsa;NON_KEYWORDS=brand
    driver-class-name: org.h2.Driver
    username: sa
    password:
    generate-unique-name: false
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          import_files: import.sql

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
app:
  cors:
    allowed-origins: http://localhost:3000